"""
Multilingual strings dictionary for Market Seller GUI.
"""

STRINGS = {
    "en": {
        "app_title": "Market Seller — Auto Clicker & Smart OCR",
        "header_title": "MARKET SELLER AUTO CLICKER",
        "tab_positions": "Positions & Controls",
        "tab_settings": "Settings",
        "section_positions": "Click Positions",
        "btn_wizard": "Setup Wizard (3 Click)",
        "label_pos_a": "Pos A",
        "label_pos_b": "Pos B",
        "label_pos_c": "Pos C",
        "btn_test": "Test",
        "btn_capture": "Capture",
        "section_controls": "Controls",
        "label_hotkey": "Toggle Hotkey:",
        "section_log": "Activity Log",
        "btn_start": "▶ START",
        "btn_stop": "■ STOP",
        "section_timing": "Timing & Delays (Milliseconds)",
        "label_delay_ab": "Delay after Pos A (Open Item):",
        "label_delay_bc": "Delay after Pos B (Undercut [-]):",
        "label_delay_ca": "Delay after Pos C (Create Order):",
        "label_delay_ocr": "Delay before OCR read:",
        "section_antidetect": "Anti-Detection & Humanization",
        "switch_human_mouse": "Humanized Bézier Mouse Movement",
        "switch_human_type": "Humanized Typing Simulation",
        "switch_jitter": "Random Timing Jitter (±15%)",
        "label_max_items": "Max Items to Sell (0 = Infinite):",
        "label_language": "Language:",
        "btn_save_settings": "💾 Save Settings",
        "wizard_step_1": "[Wizard] Step 1/3: Position A (first click) -> Click 'Sell' on the top item",
        "wizard_step_2": "[Wizard] Step 2/3: Position B (second click) -> Click '[-]' price decrement button",
        "wizard_step_3": "[Wizard] Step 3/3: Position C (third click) -> Click 'Create' order button",
        "wizard_complete": "[Wizard] All 3 positions set! You're ready to start.",
        "capture_single": "[Capture] Click anywhere to set {}...",
        "capture_done": "[Capture] {} set to ({}, {})",
        "loop_started": "[Control] Clicking started - A -> B -> C loop",
        "loop_stopped": "[Control] Clicking stopped. Total items sold: {}",
        "cycle_sold": "[Cycle #{}] Sold item at Pos A -> B -> C",
        "status_ready": "Ready",
        "status_running": "Running",
        "status_wizard": "Wizard Active...",
        "mode_label": "Operating Mode:",
        "mode_3point": "⚡ 3-Point Fast ([-])",
        "mode_ocr": "🧠 Smart OCR (Price + %)",
        "section_ocr_coords": "Smart OCR Coordinates",
        "label_pos_sell": "Pos Sell (Item)",
        "label_price_box": "Price Area (OCR)",
        "label_price_input": "Price Input Field",
        "label_create_order": "Create Order Button",
        "section_pricing": "Pricing Strategy & Discount",
        "label_discount_percent": "Discount Percentage (%):",
        "label_floor_price": "Safety Floor Price (Silver):",
        "label_strategy_type": "Discount Strategy:",
        "btn_test_ocr": "🔍 Test OCR",
        "btn_capture_area": "Capture Box",
        "btn_wizard_ocr": "OCR Wizard (4 Steps)",
        "ocr_test_result": "[OCR Test] Detected: {:,} Silver | Target: {:,} Silver ({})",
        "ocr_read_fail": "❌ Could not read price from screen area.",
        "ocr_below_floor": "⚠️ Detected price ({:,}) is below floor price ({:,}). Item protected!",
        "ocr_sold": "[Cycle #{}] Detected: {:,} -> Sold at {:,} Silver ({})",
        "label_tesseract": "Tesseract Executable:",
        "btn_browse_tesseract": "📁 Browse...",
        "btn_detect_tesseract": "🔍 Auto-Detect",
        "tesseract_found": "✅ Tesseract located at: {}",
        "tesseract_not_found": "⚠️ Tesseract not found. Please specify path or install Tesseract OCR.",
        "region_map": {
            "sell_button": "Sell Tab Button",
            "order_button": "Sell Order Button",
            "price_input": "Price Input Field",
            "submit_button": "Create Order Button",
            "price_value": "Current Price Area",
            "average_price": "Average Price Area",
        },
    },
    "it": {
        "app_title": "Market Seller — Auto Clicker & Smart OCR",
        "header_title": "MARKET SELLER AUTO CLICKER",
        "tab_positions": "Posizioni & Controlli",
        "tab_settings": "Impostazioni",
        "section_positions": "Posizioni di Click",
        "btn_wizard": "Setup Wizard (3 Click)",
        "label_pos_a": "Pos A",
        "label_pos_b": "Pos B",
        "label_pos_c": "Pos C",
        "btn_test": "Test",
        "btn_capture": "Cattura",
        "section_controls": "Controlli",
        "label_hotkey": "Tasto Rapido Avvio/Stop:",
        "section_log": "Log Attività",
        "btn_start": "▶ AVVIA",
        "btn_stop": "■ FERMA",
        "section_timing": "Tempi & Ritardi (Millisecondi)",
        "label_delay_ab": "Ritardo dopo Pos A (Apertura Oggetto):",
        "label_delay_bc": "Ritardo dopo Pos B (Sconto [-]):",
        "label_delay_ca": "Ritardo dopo Pos C (Crea Ordine):",
        "label_delay_ocr": "Ritardo prima di lettura OCR:",
        "section_antidetect": "Anti-Rilevamento & Umanizzazione",
        "switch_human_mouse": "Movimento Mouse Naturale (Bézier)",
        "switch_human_type": "Digitazione Umana Naturale",
        "switch_jitter": "Variazione Casuale Ritardi (±15%)",
        "label_max_items": "Max Oggetti da Vendere (0 = Infinito):",
        "label_language": "Lingua:",
        "btn_save_settings": "💾 Salva Impostazioni",
        "wizard_step_1": "[Wizard] Passo 1/3: Posizione A (primo click) -> Fai click su 'Sell' del primo oggetto",
        "wizard_step_2": "[Wizard] Passo 2/3: Posizione B (secondo click) -> Fai click sul tasto '[-]' del prezzo",
        "wizard_step_3": "[Wizard] Passo 3/3: Posizione C (terzo click) -> Fai click sul tasto 'Create' ordine",
        "wizard_complete": "[Wizard] Tutte e 3 le posizioni impostate! Pronto per iniziare.",
        "capture_single": "[Cattura] Fai click ovunque sullo schermo per impostare {}...",
        "capture_done": "[Cattura] {} impostato su ({}, {})",
        "loop_started": "[Controllo] Avviato ciclo di vendita - Loop A -> B -> C",
        "loop_stopped": "[Controllo] Ciclo fermato. Oggetti totali venduti: {}",
        "cycle_sold": "[Ciclo #{}] Venduto oggetto con Pos A -> B -> C",
        "status_ready": "Pronto",
        "status_running": "In Esecuzione",
        "status_wizard": "Wizard Attivo...",
        "mode_label": "Modalità Operativa:",
        "mode_3point": "⚡ 3-Point Veloce ([-])",
        "mode_ocr": "🧠 Smart OCR (Prezzo + %)",
        "section_ocr_coords": "Coordinate Smart OCR",
        "label_pos_sell": "Pos Vendita (Oggetto)",
        "label_price_box": "Area Prezzo (OCR)",
        "label_price_input": "Campo Input Prezzo",
        "label_create_order": "Pulsante Crea Ordine",
        "section_pricing": "Strategia Prezzo & Sconto",
        "label_discount_percent": "Sconto Percentuale (%):",
        "label_floor_price": "Prezzo Minimo Floor (Silver):",
        "label_strategy_type": "Strategia di Sconto:",
        "btn_test_ocr": "🔍 Test OCR",
        "btn_capture_area": "Cattura Area",
        "btn_wizard_ocr": "Setup Wizard OCR (4 Step)",
        "ocr_test_result": "[Test OCR] Rilevato: {:,} Silver | Calcolato: {:,} Silver ({})",
        "ocr_read_fail": "❌ Impossibile leggere il prezzo dall'area indicata.",
        "ocr_below_floor": "⚠️ Prezzo rilevato ({:,}) inferiore al prezzo minimo ({:,}). Oggetto protetto!",
        "ocr_sold": "[Ciclo #{}] Rilevato: {:,} -> Venduto a {:,} Silver ({})",
        "label_tesseract": "Eseguibile Tesseract:",
        "btn_browse_tesseract": "📁 Sfoglia...",
        "btn_detect_tesseract": "🔍 Rileva Automaticamente",
        "tesseract_found": "✅ Tesseract trovato su: {}",
        "tesseract_not_found": "⚠️ Tesseract non trovato. Specifica il percorso o installa Tesseract OCR.",
        "region_map": {
            "sell_button": "Sell Tab Button",
            "order_button": "Sell Order Button",
            "price_input": "Price Input Field",
            "submit_button": "Create Order Button",
            "price_value": "Current Price Area",
            "average_price": "Average Price Area",
        },
    },
}
